#!/bin/bash

lshw -c network -businfo >/tmp/nicinfo 2>/dev/null
lshw -c video -businfo | sed 's/pci\@0000://g' >/tmp/gpuinfo 2>/dev/null

IPs=$(ip addr list | grep "state UP" | awk '{print $2}' | tr -d ':')

for f in $IPs
do

echo === $f NUMA $(cat /sys/class/net/$f/device/numa_node) ===

(ethtool $f | grep Speed) 2>/dev/null
grep $f /tmp/nicinfo

done

echo ==== Video ===


cat /tmp/gpuinfo

for f in $(grep display /tmp/gpuinfo | awk '{print $1}')
do

    echo ==== $f ====

    lspci -vv | grep -w $f -A20 | egrep -i '(numa|speed|lnk)'
done
