translateType trans_mi[] = {
			    {"Abort", "Whakakore", "KKH"},
			    {"Apply", "Whakamahi", ""},
			    {"Available", "Wātea", ""},
			    {"Backup", "Tiaki tūemi", ""},
			    {"Bit", "moka", "MSOFT (binary digit)"},
			    {"Block device count", "Tau Pūrere Pūtau", ""},
			    {"Block device", "taonga mahi wāhanga", "Mandrake"},
			    {"Boot", "whakaoho", "WWOW (load first piece of software)"},
			    {"Break", "motu", "MSOFT"}, 
			    {"Byte", "paita", "Google"},
			    {"CPU Cores", "Nga matua CPU", "Google"},
			    {"CPU", "CPU", "Google"},
			    {"Calc entropy of a string", "Tātai entropi o te whakaharatau", ""},
			    {"Cancel", "Whakakore", "KKM|Google"},
			    {"Client connects to a server for tests", "Kiritaki hono ki tētahi tūmau mō ngā whakamātautau", ""},
			    {"Close", "Kati", "Mandrake|Google"},
			    {"Cluster", "Rōpū whakarite pūrua", ""},
			    {"Collapse", "Tiango", "MSOFT|Google"},
			    {"Commands", "Whakahau", "Google"},
			    {"Confirm", "whakaū", "MSOFT|Google"},
			    {"Copy", "Kape", "Kupu|Google (copy a file)"},
			    {"Count", "Tatau", "Moodle|Google"},
			    {"Create", "Waihanga", "msoft"},
			    {"Cron job", "Tūnga Cron", ""},
			    {"Current directory", "kōpaki mahi", "WWOW"},
			    {"Cut", "Tapahi", "Kupu"},
			    {"DNS", "Pūnaha Ingoa-Ipurangi", "WWOW"},
			    {"Daemon", "tiamana", ""},
			    {"Database", "Pūranga kōrero", "TMT"},
			    {"Decompress", "roha", "Msoft (expand)"},
			    {"Delete", "Mukua", "MSOFT"},
			    {"Deselect", "whakawātea", "msoft"},
			    {"Directory", "kōpaki", "WWOW"},
			    {"Disk free", "Mokowā kōpae wātea", "Msoft"},
			    {"Disk space", "Mokowā kōpae", "Msoft"},
			    {"Domain name system", "Pūnaha Ingoa-Ipurangi", "WWOW"},
			    {"Domain name", "Ingoa ipurangi", "WWOW"},
			    {"Domain", "Rohe", "(Windows AD domain)"},
			    {"Download", "Tikiake", "msoft"},
			    {"Dropbear SSH config", "Whirihoranga SSH Dropbear", ""},
			    {"Edit", "Whakatika", "WWOW"},
			    {"Environment variables", "Tūemi taiao", ""},
			    {"Examples", "Ngā tauira", "M.T."},
			    {"Exit the secure shell", "Whakakore i te kiriata haumaru", ""},
			    {"Exit", "whakamutu", "WWOW"},
			    {"Expand", "whakamutu", "msoft (opposite of collapse)"},
			    {"File", "Kōnae", "TMT"},
			    {"Filesystem", "tātai kōpaki", "TMT"},
			    {"Filter", "Ngā Āpure", ""},
			    {"Firewall", "pātūahi", "WWOW"},
			    {"Free (GB)", "Wātea (GB)", ""},
			    {"Free RAM", "Pūmahara wātea", "msoft (available memory)"},
			    {"Generate cryptographically complex 200-bit random password", "Hanga kupuhipa matatini whakakotahitanga 200-bit", ""},
			    {"Goodbye", "Haere rā", "M.T."},
			    {"Group", "Rōpū", "Mandrake"},
			    {"HTML", "Reo Tuhinga-Itua", "WWOW"},
			    {"Hardware Type", "Momo Pūkenga", "(server desktop or NUC)"},
			    {"Hello", "Kia ora", ""},
			    {"Host", "Kaihautū", "Msoft"},
			    {"IP address", "Nohoanga Kawa Ipurangi", "WWOW"},
			    {"Is the terminal interactive", "He whakawhiti te tātārua", ""},
			    {"Kernel", "roho", ""},
			    {"List IP/HW addresses", "Whakaatu IP/Ngā wāhitau hangarau", ""},
			    {"List drive block devices", "Whakaatu pūtau pūrere", ""},
			    {"List translations", "Rārangi whakamāoritanga", ""},
			    {"Lists the number of processes", "Whakaatu i te tātau o ngā tukanga", ""},
			    {"Load balancing", "Whakararuraru whakarau", ""},
			    {"Load", "taumaha pūnaha", "(system load/util)"},
			    {"Location", "Tūnga", ""},
			    {"Log in", "whakauru", "WWOW"},
			    {"Log out", "whakarere", "TT"},
			    {"Log", "rangitaki", "msoft"},
			    {"Measure read speed on device", "Ine tere pānui o te pūrere", ""},
			    {"Monitoring", "Tiaki", ""},
			    {"Mount point", "Pātengi Raraunga", ""},
			    {"Navigate", "urungi", "WWOW"},
			    {"Network", "whatunga", "msoft"},
			    {"No", "Kāo", ""},
			    {"Not available", "kore āhei", "msoft"},
			    {"OK", "ka pai", "MSOFT"},
			    {"OS Type", "Pūmanawa whakahaere", "WWOW"},
			    {"Open", "Whakatūwhera", "M.T."},
			    {"Package", "kaupapa whāiti", "Moodle"},
			    {"Packet", "mōkihi mōhiohio", "WWOW"},
			    {"Paste", "Whakapiri", "RF"},
			    {"Path", "Nohoanga kōnae", "WWOW (path name)"},
			    {"Permissions", "Whakaaetanga", ""},
			    {"Point of presence (POP)", "hononga (ipurangi) tata", "TT"},
			    {"Power saving mode", "kaitiaki hiko", "WWOW"},
			    {"Proceed", "Haere Tonu", ""},
			    {"Process", "Tukanga", ""},
			    {"RAID", "Rārangi Whakakore Tūmataiti", ""},
			    {"Reboot", "kikipa anō", "msoft"},
			    {"Redo", "Mahia Anō", "msoft"},
			    {"Refresh", "tāmata", "msoft"},
			    {"Reject", "ākiri", "msoft"},
			    {"Restart", "tīmata anō", "RF"},
			    {"Root", "Pūtake", ""},
			    {"SSH Passwords", "SSH Kupuhipa", ""},
			    {"SSL certificate", "Tohu SSL", ""},
			    {"Save", "Tiaki", "WWOW"},
			    {"Search", "Rapu", "WWOW"},
			    {"Select", "Kōwhiri", "WWOW"},
			    {"Service", "Ratonga", "msoft"},
			    {"Set locale language", "Whakatakoto reo", ""},
			    {"Shell", "Kiri", ""},
			    {"Show CPU info", "Whakaatu pūnaha", ""},
			    {"Show SCSI devices", "Whakaatu pūrere SCSI", ""},
			    {"Show mounts info", "Whakaatu pātengi raraunga", ""},
			    {"Show system status", "Whakaatu tūnga pūnaha", ""},
			    {"Show the current date/time", "Whakaatu rā/tāima o nāianei", ""},
			    {"Shutdown", "Katia", ""},
			    {"Sort", "Kōmaka", "M.T."},
			    {"Starts server for network tests", "Tīmata tūmau mō ngā whakamātautau whāngaihono", ""},
			    {"Stu's powerful I/O tester", "Te whakamātaitai I/O kaha a Stu", ""},
			    {"Submit", "Tuku", "msoft"},
			    {"Support", "Awhina", "moodle (help)"},
			    {"Swap space", "Wāhi Whakakapi", ""},
			    {"System", "Pūnaha", "WWOW"},
			    {"Terminal", "kāpeka rorohiko", "Ryan"},
			    {"Toggle", "toke", "msoft"},
			    {"Total (GB)", "Tapeke (GB)", "(total space in GB)"},
			    {"Total RAM", "pūmahara", ""},
			    {"Type ? or help to list commands", "Pāwhiritia ? or āwhina hei whakaatu i ngā whakahau", ""},
			    {"Undo", "Whakakore", "TTW"},
			    {"Unknown command", "Whakahau kore e mōhio ana", ""},
			    {"Update", "Whakahōu", "Mandrake"},
			    {"Upload", "tuku atu", "WWOW"},
			    {"Uptime (days)", "Wā whakahaere (ra)", ""},
			    {"Use%", "Whakamahinga%", "(disk use as a percentage)"},
			    {"User", "kaiwhakuru", "Moodle"},
			    {"Utilization", "Whakamahinga", "(the percent load of the machine)"},
			    {"Virtual server", "tūmau mariko", "msoft"},
			    {"Web server", "Tūmauwhakahaere", ""},
			    {"Yes", "Āe", ""},
			    {"bits of entropy", "kupuhipa o te entropi", ""},
			    {"generate random bits for length", "Hanga kupuhipa matatini whakakotahitanga", ""},
			    {"password is weak and is below complexity target","Kāore te kupuhipa i te tino whakakotahitanga, ā, kei raro i te whāinga whakahiranga", ""},
			    {"secure sandpit", "Pātaka ārai haumaru", ""},
			    {"usage", "kōrerotanga", "Mandrake (command line example)"}
};
