translateType trans_mi[] = {
			    {"Abort", "Whakakore"},
			    {"Apply", "Whakamahi"},
			    {"Available", "Wātea"},
			    {"Backup", "Tiaki tūemi"},
			    {"Block device count", "Tau Pūrere Pūtau"},
			    {"CPU Cores", "Ngā Kēnga"},
			    {"CPU Model", "Momo Tīhanga"},
			    {"Calc entropy of a string", "Tātai entropi o te reta"},
			    {"Cancel", "Whakakore"},
			    {"Close", "Katia"},
			    {"Cluster", "Rōpū whakarite pūrua"},
			    {"Collapse", "Katia"},
			    {"Commands", "Whakahau"},
			    {"Confirm", "Whakamanahia"},
			    {"Copy", "Tāruatia"},
			    {"Count", "Tatau"},
			    {"Create", "Waihanga"},
			    {"Cron job", "Tūnga Cron"},
			    {"Cut", "Takahi"},
			    {"Daemon", "tiamana"},
			    {"Database", "Pūranga"},
			    {"Delete", "Muku"},
			    {"Deselect", "Katia te Kōwhiri"},
			    {"Directory", "Kawenga"},
			    {"Disk free", "Pūtau wātea"},
			    {"Domain", "Rohe"},
			    {"Download", "Tikiake"},
			    {"Dropbear SSH config", "Whirihoranga SSH Dropbear"},
			    {"Edit", "Whakatika"},
			    {"Environment variables", "Tūemi taiao"},
			    {"Examples", "Whakarāpopototanga"},
			    {"Exit the secure shell", "Whakakore i te kiriata haumaru"},
			    {"Expand", "Whakarahi"},
			    {"File", "Kōnae"},
			    {"Filesystem", "Raraunga whāinga"},
			    {"Filter", "Ngā Āpure"},
			    {"Firewall", "Pūnaha whakamaunu"},
			    {"Free (GB)", "Wātea (GB)"},
			    {"Free RAM", "Mahara wātea"},
			    {"Generate cryptographically complex 200-bit random password", "Hanga kupuhipa matatini whakakotahitanga 200-bit"},
			    {"Goodbye", "Kia pai tō rā"},
			    {"Group", "Rōpū"},
			    {"Hardware Type", "Momo Pūkenga"},
			    {"Hello", "Kia ora"},
			    {"Host", "Kaiwhakahaere"},
			    {"IP address", "Wāhitau IP"},
			    {"Is the terminal interactive", "He whakawhitiwhitiwhiti te tātārua"},
			    {"Kernel", "Kērara"},
			    {"List IP/HW addresses", "Whakaatu IP/Ngā wāhitau hangarau"},
			    {"List drive block devices", "Whakaatu pūtau pūrere"},
			    {"List translations", "Rārangi whakamāoritanga"},
			    {"Lists the number of processes", "Whakaatu i te tātau o ngā tukanga"},
			    {"Load balancing", "Whakararuraru whakarau"},
			    {"Load", "Whakararu"},
			    {"Location", "Tūnga"},
			    {"Log in", "Takiuru"},
			    {"Log out", "Whakakore Takiurunga"},
			    {"Log", "Rorohiko"},
			    {"Measure read speed on device", "Ine tere pānui o te pūrere"},
			    {"Monitoring", "Tiaki"},
			    {"Mount point", "Pātengi Raraunga"},
			    {"Navigate", "Haereere"},
			    {"Network", "Whāngaihono"},
			    {"No", "Kāo"},
			    {"Not available", "Kāore e wātea"},
			    {"OK", "Tika"},
			    {"OS Type", "Pūnaha Whakahaere"},
			    {"Open", "Whakatuwhera"},
			    {"Package", "Pakete"},
			    {"Paste", "Whakapiri"},
			    {"Path", "Ara"},
			    {"Permissions", "Whakaaetanga"},
			    {"Power saving mode", "Aratau Whakaiti Hiko"},
			    {"Proceed", "Haere Tonu"},
			    {"Process", "Tukanga"},
			    {"RAID", "Rārangi Whakakore Tūmataiti"},
			    {"Redo", "Mahia Anō"},
			    {"Refresh", "Whakahōu"},
			    {"Reject", "Whakahē"},
			    {"Restart", "Whakahōu"},
			    {"Root", "Pūtake"},
			    {"SSH Passwords", "SSH Kupuhipa"},
			    {"SSL certificate", "Tohu SSL"},
			    {"Save", "Tiaki"},
			    {"Search", "Rapu"},
			    {"Select", "Kōwhiria"},
			    {"Service", "Ratonga"},
			    {"Set locale language", "Whakatakoto reo"},
			    {"Shell", "Kiri"},
			    {"Show CPU info", "Whakaatu pūnaha"},
			    {"Show SCSI devices", "Whakaatu pūrere SCSI"},
			    {"Show mounts info", "Whakaatu pātengi raraunga"},
			    {"Show system status", "Whakaatu tūnga pūnaha"},
			    {"Show the current date/time", "Whakaatu rā/tāima o nāianei"},
			    {"Shutdown", "Katia"},
			    {"Sort", "Whakarōpu"},
			    {"Stu's powerful I/O tester", "Te whakamātaitai I/O kaha a Stu"},
			    {"Submit", "Tuku"},
			    {"Support", "Tautoko"},
			    {"Swap space", "Wāhi Whakakapi"},
			    {"System", "Pūnaha"},
			    {"Terminal", "Whakatereti"},
			    {"Toggle", "Whakakapi"},
			    {"Total (GB)", "Tapeke (GB)"},
			    {"Total RAM", "Mahara Katoa"},
			    {"Type ? or help to list commands", "Pāwhiritia ? or āwhina hei whakaatu i ngā whakahau"},
			    {"Undo", "Whakakore"},
			    {"Unknown command", "Whakahau kore e mōhio ana"},
			    {"Update", "Whakahōu"},
			    {"Upload", "Tuku"},
			    {"Uptime (days)", "Wā whakahaere (ra)"},
			    {"Use%", "Whakamahinga%"},
			    {"User", "Kaiwhakamahi"},
			    {"Utilization", "Whakamahinga"},
			    {"Virtualization", "Ahurewa whakaora"},
			    {"Web server", "Tūmauwhakahaere"},
			    {"Yes", "Āe"},
			    {"secure sandpit", "Pātaka ārai haumaru"},
			    {"usage", "whakamahi"},
};
