translateType trans_mi[] = {
			    {"Abort", "Whakakore", "KKH"},
			    {"Apply", "Whakamahi", ""},
			    {"Available", "Wātea", ""},
			    {"Backup", "Tiaki tūemi", ""},
			    {"Bit", "moka|binary digit", "MSOFT"},
			    {"bits of entropy", "kupuhipa o te entropi", ""},
			    {"Block device", "taonga mahi wāhanga", "Mandrake"},
			    {"Block device count", "Tau Pūrere Pūtau", ""},
			    {"Boot", "whakaoho|the load the first piece of software", "WWOW"},
			    {"Break", "motu", "MSOFT"}, 
			    {"CPU Cores", "Nga matua CPU", "Google"},
			    {"CPU", "CPU", "Google"},
			    {"Calc entropy of a string", "Tātai entropi o te whakaharatau", ""},
			    {"Cancel", "Whakakore", "KKM|Google"},
			    {"Close", "Kati", "Mandrake|Google"},
			    {"Cluster", "Rōpū whakarite pūrua", ""},
			    {"Collapse", "Tiango", "MSOFT|Google"},
			    {"Commands", "Whakahau", "Google"},
			    {"Confirm", "whakaū", "MSOFT|Google"},
			    {"Copy", "Kape|copy a file", "Kupu|Google"},
			    {"Count", "Tatau", "Moodle|Google"},
			    {"Create", "Waihanga", "msoft"},
			    {"Cron job", "Tūnga Cron", ""},
			    {"Cut", "Tapahi", "Kupu"},
			    {"Daemon", "tiamana", ""},
			    {"Database", "Pūranga kōrero", "TMT"},
			    {"Delete", "Mukua", "MSOFT"},
			    {"Deselect", "whakawātea", "msoft"},
			    {"Directory", "kōpaki", "WWOW"},
			    {"Current directory", "kōpaki mahi", "WWOW"},
			    {"Decompress", "roha|expand", "Msoft"},
			    {"Disk space", "Mokowā kōpae", "Msoft"},
			    {"Disk free", "Mokowā kōpae wātea", "Msoft"},
			    {"DNS", "Pūnaha Ingoa-Ipurangi", "WWOW"},
			    {"Domain name system", "Pūnaha Ingoa-Ipurangi", "WWOW"},
			    {"Domain name", "Ingoa ipurangi", "WWOW"},
			    {"Domain", "Rohe|context of Windows NT/AD domain", ""},
			    {"Download", "Tikiake", "msoft"},
			    {"Dropbear SSH config", "Whirihoranga SSH Dropbear", ""},
			    {"Edit", "Whakatika", "WWOW"},
			    {"Environment variables", "Tūemi taiao", ""},
			    {"Examples", "Ngā tauira", "M.T."},
			    {"Exit", "whakamutu", "WWOW"},
			    {"Exit the secure shell", "Whakakore i te kiriata haumaru", ""},
			    {"Expand", "whakamutu|opposite of collapse", "msoft"},
			    {"File", "Kōnae", "TMT"},
			    {"Filesystem", "tātai kōpaki", "TMT"},
			    {"Filter", "Ngā Āpure", ""},
			    {"Firewall", "pātūahi", "WWOW"},
			    {"Free (GB)", "Wātea (GB)", ""},
			    {"Free RAM", "Pūmahara wātea|available memory", "msoft"},
			    {"generate random bits for length", "Hanga kupuhipa matatini whakakotahitanga", ""},
			    {"Generate cryptographically complex 200-bit random password", "Hanga kupuhipa matatini whakakotahitanga 200-bit", ""},
			    {"Goodbye", "Haere rā", "M.T."},
			    {"Group", "Rōpū", "Mandrake"},
			    {"Hardware Type", "Momo Pūkenga|Is it a server, or desktop or small NUC", ""},
			    {"Hello", "Kia ora|Welcome to using the app", ""},
			    {"Host", "Kaihautū", "Msoft"},
			    {"HTML", "Reo Tuhinga-Itua", "WWOW"},
			    {"IP address", "Nohoanga Kawa Ipurangi", "WWOW"},
			    {"Is the terminal interactive", "He whakawhiti te tātārua", ""},
			    {"Kernel", "roho", ""},
			    {"List IP/HW addresses", "Whakaatu IP/Ngā wāhitau hangarau", ""},
			    {"List drive block devices", "Whakaatu pūtau pūrere", ""},
			    {"List translations", "Rārangi whakamāoritanga", ""},
			    {"Lists the number of processes", "Whakaatu i te tātau o ngā tukanga", ""},
			    {"Load balancing", "Whakararuraru whakarau", ""},
			    {"Load", "taumaha pūnaha|load meaning system load/utilization", ""},
			    {"Location", "Tūnga", ""},
			    {"Log in", "whakauru", "WWOW"},
			    {"Log out", "whakarere", "TT"},
			    {"Log", "rangitaki", "msoft"},
			    {"Measure read speed on device", "Ine tere pānui o te pūrere", ""},
			    {"Monitoring", "Tiaki", ""},
			    {"Mount point", "Pātengi Raraunga", ""},
			    {"Navigate", "urungi", "WWOW"},
			    {"Starts server for network tests", "Tīmata tūmau mō ngā whakamātautau whāngaihono", ""},
			    {"Client connects to a server for tests", "Kiritaki hono ki tētahi tūmau mō ngā whakamātautau", ""},
			    {"Network", "whatunga", "msoft"},
			    {"No", "Kāo", ""},
			    {"Not available", "kore āhei", "msoft"},
			    {"OK", "ka pai", "MSOFT"},
			    {"OS Type", "Pūmanawa whakahaere", "WWOW"},
			    {"Open", "Whakatūwhera", "M.T."},
			    {"Packet", "mōkihi mōhiohio", "WWOW"},
			    {"Package", "kaupapa whāiti", "Moodle"},
			    {"password is weak and is below complexity target","Kāore te kupuhipa i te tino whakakotahitanga, ā, kei raro i te whāinga whakahiranga", ""},
			    {"Paste", "Whakapiri", "RF"},
			    {"Path", "Nohoanga kōnae|path name", "WWOW"},
			    {"Permissions", "Whakaaetanga", ""},
			    {"Power saving mode", "kaitiaki hiko", "WWOW"},
			    {"Point of presence (POP)", "hononga (ipurangi) tata", "TT"},
			    {"Proceed", "Haere Tonu", ""},
			    {"Process", "Tukanga", ""},
			    {"RAID", "Rārangi Whakakore Tūmataiti", ""},
			    {"Reboot", "kikipa anō", "msoft"},
			    {"Redo", "Mahia Anō", "msoft"},
			    {"Refresh", "tāmata", "msoft"},
			    {"Reject", "ākiri", "msoft"},
			    {"Restart", "tīmata anō", "RF"},
			    {"Root", "Pūtake", ""},
			    {"SSH Passwords", "SSH Kupuhipa", ""},
			    {"SSL certificate", "Tohu SSL", ""},
			    {"Save", "Tiaki", "WWOW"},
			    {"Search", "Rapu", "WWOW"},
			    {"Select", "Kōwhiri", "WWOW"},
			    {"Service", "Ratonga", "msoft"},
			    {"Set locale language", "Whakatakoto reo", ""},
			    {"Shell", "Kiri", ""},
			    {"Show CPU info", "Whakaatu pūnaha", ""},
			    {"Show SCSI devices", "Whakaatu pūrere SCSI", ""},
			    {"Show mounts info", "Whakaatu pātengi raraunga", ""},
			    {"Show system status", "Whakaatu tūnga pūnaha", ""},
			    {"Show the current date/time", "Whakaatu rā/tāima o nāianei", ""},
			    {"Shutdown", "Katia", ""},
			    {"Sort", "Kōmaka", "M.T."},
			    {"Stu's powerful I/O tester", "Te whakamātaitai I/O kaha a Stu", ""},
			    {"Submit", "Tuku", "msoft"},
			    {"Support", "Awhina|help", "moodle"},
			    {"Swap space", "Wāhi Whakakapi", ""},
			    {"System", "Pūnaha", "WWOW"},
			    {"Terminal", "kāpeka rorohiko", "Ryan"},
			    {"Toggle", "toke", "msoft"},
			    {"Total (GB)", "Tapeke (GB)|total disk space in gigabytes", ""},
			    {"Total RAM", "pūmahara", ""},
			    {"Type ? or help to list commands", "Pāwhiritia ? or āwhina hei whakaatu i ngā whakahau", ""},
			    {"Undo", "Whakakore", "TTW"},
			    {"Unknown command", "Whakahau kore e mōhio ana", ""},
			    {"Update", "Whakahōu", "Mandrake"},
			    {"Upload", "tuku atu", "WWOW"},
			    {"Uptime (days)", "Wā whakahaere (ra)", ""},
			    {"Use%", "Whakamahinga%|the disk use as a percentage", ""},
			    {"User", "kaiwhakuru", "Moodle"},
			    {"Utilization", "Whakamahinga|the percent load of the machine", ""},
			    {"Virtual server", "tūmau mariko", "msoft"},
			    {"Web server", "Tūmauwhakahaere", ""},
			    {"Yes", "Āe", ""},
			    {"secure sandpit", "Pātaka ārai haumaru", ""},
			    {"usage", "kōrerotanga|used as used: command line example", "Mandrake"}
};
